In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.46836841, 0.43644549, 0.67850551, 0.89638866, 0.9937577 ])

In [30]:
np.random.rand(5,5)

array([[0.06493406, 0.13241705, 0.6590016 , 0.26344349, 0.19561046],
       [0.05651489, 0.90706368, 0.3148364 , 0.3913623 , 0.26393878],
       [0.25992792, 0.86350143, 0.31678862, 0.17243539, 0.9006806 ],
       [0.41363712, 0.42605803, 0.6368238 , 0.88877103, 0.18303739],
       [0.20463979, 0.04451951, 0.39879922, 0.06914627, 0.40060482]])

In [33]:
np.random.randn(2,2)

array([[ 6.11925342e-01, -2.01017905e-04],
       [ 7.84340884e-01,  1.97117833e+00]])

In [35]:
np.random.randint(1,100,10)

array([46, 14, 97, 52, 32, 94, 72, 56, 94, 33])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([30, 10, 12,  5, 16, 13, 22, 35, 39, 35])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr.max()

39

In [51]:
ranarr.min()

5

In [53]:
ranarr.argmax()
#index location of ranarr.max()

8

In [56]:
arr = arr.reshape(5,5)

In [57]:
arr.shape


(5, 5)

In [58]:
arr.dtype

dtype('int64')

In [61]:
from numpy.random import randint
randint(2,10)

7

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[5]

5

In [9]:
arr[1:4]

array([1, 2, 3])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr = np.arange(0,11)

In [26]:
slice_of_arr = arr[0:6]

In [28]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [31]:
slice_of_arr[:] = 88

In [32]:
slice_of_arr

array([88, 88, 88, 88, 88, 88])

In [33]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [34]:
arr_copy = arr.copy()

In [35]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [36]:
arr_copy

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [37]:
arr_copy[:] = 100

In [38]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [63]:
arr_2d = np.array([[5,10,15,16,18], [20,25,30,16,18], [35,40,45,16,18], [35,40,45,16,18], [35,40,45,16,18]])

In [64]:
arr_2d

array([[ 5, 10, 15, 16, 18],
       [20, 25, 30, 16, 18],
       [35, 40, 45, 16, 18],
       [35, 40, 45, 16, 18],
       [35, 40, 45, 16, 18]])

In [65]:
arr_2d[1,2]

30

In [66]:
arr_2d[:2,1:]

array([[10, 15, 16, 18],
       [25, 30, 16, 18]])

In [67]:
arr_2d[:3,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [68]:
#conditional selection

In [69]:
arr = np.arange(1,11)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [73]:
bool_arr = arr > 5

In [75]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
a = arr[bool_arr]

In [100]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [101]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [102]:
arr_2d = np.arange(50).reshape(5,10)

In [103]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [106]:
#NUMPY operations

In [107]:
import numpy as np

In [109]:
arr = np.arange(0,11)

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [112]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [114]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [116]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [117]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [118]:
arr / arr

<ipython-input-118-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [119]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [120]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [121]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [122]:
np.max(arr)

10

In [123]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [127]:
np.min(arr)

0

In [128]:
np.mean(arr)

5.0